#!/bin/bash
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir
properties=${1:-JennyRoslyn.properties}
echo "pwd:"
pwd
echo "dir=$dir"
echo "properties=$properties"
dotnet ./Jenny/Jenny.Generator.Cli.dll gen "$properties" -v
